# Pytorch로 딥러닝 제대로 배우기-기초
## Part3: 텐서(Tensor)
### 1. 텐서 기초

#### (1) 텐서 생성

In [1]:
import torch
import numpy as np

In [2]:
# 데이터로부터 직접 생성
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
# Numpy 배열로부터 생성
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
# 다른 텐서로부터 생성
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8937, 0.5600],
        [0.8466, 0.4368]]) 



In [5]:
# 랜덤하게 또는 상수 변수로 생성
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.9079, 0.1589, 0.7393],
        [0.4403, 0.0274, 0.5623]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


#### (2) 텐서의 속성

In [6]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

tensor = tensor.to('cuda')
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu
Device tensor is stored on: cuda:0


In [7]:
# 같은 디바이스 내에 있는 텐서끼리만 연산 가능!!
cpu_tensor = torch.ones(3)
gpu_tensor = torch.ones(3).to('cuda')
tensor_sum = cpu_tensor + gpu_tensor
print(f"Tensor sum: {tensor_sum}")

RuntimeError: ignored

#### (3) Tensor 연산

In [8]:
# Single-element tensors
tensor = torch.ones(3,3)
agg = tensor.sum()
agg_item = agg.item()
print(tensor)
print(agg_item, type(agg_item))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
9.0 <class 'float'>


In [9]:
print(tensor)

# Normal operation
tensor.add(5)
print(tensor)

# In-place operation
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


#### (4) Bridge with Numpy

In [10]:
# Tensor to Numpy
t = torch.ones(5)
n = t.numpy()

print(f"t: {t}")
print(f"n: {n}")

# 주의할 점은 텐서가 numpy array에 영향줄 수 있음
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [11]:
# Numpy to Tensor
n = np.ones(5)
t = torch.from_numpy(n)

# 반대의 경우에도 성립
np.add(n, 1, out=n)

print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


### 2. Operation on Tensors

#### (1) Tensor 연산

In [12]:
# 텐서여부 확인
x = torch.tensor([1, 2, 3])
torch.is_tensor(x)

True

In [13]:
# Tensor가 zero인지 아닌지 판별하는 함수
# Zero가 아닌 경우에 True를 반환한다.
# Boolean에 대해서는 Boolean 값을 그대로 반환한다.
print(torch.is_nonzero(torch.tensor([0.])))
print(torch.is_nonzero(torch.tensor([1.5])))
print(torch.is_nonzero(torch.tensor([False])))
print(torch.is_nonzero(torch.tensor([True])))
print(torch.is_nonzero(torch.tensor([3])))

# is_nonzero()는 단일 텐서에 대해서만 사용 가능하다.
print(torch.is_nonzero(torch.tensor([3, 1])))


False
True
False
True
True


RuntimeError: ignored

#### Creation Operation

In [14]:
# Tensor
torch.tensor([[0.1, 1.2], [2.1, 3.6], [1.4, 8.2]])

tensor([[0.1000, 1.2000],
        [2.1000, 3.6000],
        [1.4000, 8.2000]])

In [15]:
# from numpy
a = np.array([[0.1, 1.2], [2.1, 3.6], [1.4, 8.2]])
t = torch.from_numpy(a)
t

tensor([[0.1000, 1.2000],
        [2.1000, 3.6000],
        [1.4000, 8.2000]], dtype=torch.float64)

In [16]:
# zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
# ones
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

#### (3) Indexing

In [18]:
x = torch.randn(3, 4)
x

tensor([[-0.5730, -0.0667,  1.0965,  0.8535],
        [-1.7399,  1.5116, -1.2959, -0.5611],
        [ 0.3054, -0.4194,  0.1096,  0.7473]])

In [19]:
indices = torch.tensor([0, 2])  # [0, 2]
torch.index_select(x, 0, indices) # 0번 axis를 기준으로 데이터터 호출

tensor([[-0.5730, -0.0667,  1.0965,  0.8535],
        [ 0.3054, -0.4194,  0.1096,  0.7473]])

In [20]:
torch.index_select(x, 1, indices) # 1번 axis를 기준으로 데이터 호출

tensor([[-0.5730,  1.0965],
        [-1.7399, -1.2959],
        [ 0.3054,  0.1096]])

#### (4) Slicing

In [21]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original tensor: \n{tensor}")
print(f"First row: {tensor[0]}")
print(f"Last row: {tensor[-1]}")
print(f"Second column: {tensor[:, 1]}")
print(f"Last column: {tensor[:, -1]}")

# Replace the value
tensor[:,1] = 0
tensor

Original tensor: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
First row: tensor([1, 2, 3])
Last row: tensor([7, 8, 9])
Second column: tensor([2, 5, 8])
Last column: tensor([3, 6, 9])


tensor([[1, 0, 3],
        [4, 0, 6],
        [7, 0, 9]])

#### (5) Joining

In [22]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
torch.cat((x, x, x), 0)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
torch.cat((x, x, x), 1)

tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6, 4, 5, 6],
        [7, 8, 9, 7, 8, 9, 7, 8, 9]])

#### (6) Mutating

In [25]:
# Permute
x = torch.randn(2, 3, 5)
print(x.size())
torch.permute(x, (2, 0, 1)).size()

torch.Size([2, 3, 5])


torch.Size([5, 2, 3])

In [26]:
# Reshape
a = torch.arange(4.)
print(a.size())
a = torch.reshape(a, (2, 2))
print(a.size())

b = torch.tensor([[0, 1], [2, 3]])
b = torch.reshape(b, (-1, ))
print(b)

torch.Size([4])
torch.Size([2, 2])
tensor([0, 1, 2, 3])


In [27]:
# Transpose
x = torch.randn(2, 3)
print(x)
print(x.shape)

x = torch.transpose(x, 0, 1)
print(x)
print(x.shape)

tensor([[-0.3496,  0.4201,  0.3967],
        [-1.2195,  0.8628, -1.2536]])
torch.Size([2, 3])
tensor([[-0.3496, -1.2195],
        [ 0.4201,  0.8628],
        [ 0.3967, -1.2536]])
torch.Size([3, 2])


In [28]:
# Squeeze
x = torch.zeros(2, 1, 2, 1, 2)
print(x.size())

y = torch.squeeze(x)
print(y.size())

y = torch.squeeze(x, 0)
print(y.size())

y = torch.squeeze(x, 1)
print(y.size())

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


In [29]:
# rand
torch.rand(2, 3)

tensor([[0.2888, 0.7066, 0.9484],
        [0.1490, 0.5482, 0.9000]])

### 3. Math operations

#### (1) Arithmetic operations

In [30]:
x = torch.tensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [31]:
# Matrix multiplication
y1 = x @ x.T
print(y1)

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])


In [32]:
# It is same result compare to above.
y2 = x.matmul(x.T)
print(y2)

tensor([[ 14.,  32.,  50.],
        [ 32.,  77., 122.],
        [ 50., 122., 194.]])


In [33]:
# Element-wise product
z1 = x * x
print(z1)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


In [34]:
z2 = x.mul(x)
print(z2)

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])


#### (2) Pointwize Ops

In [35]:
# absoulte
torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

In [36]:
# addition
a = torch.randn(4)
print(a)

torch.add(a, 20)

tensor([-0.1524, -0.9918,  0.2817, -1.7386])


tensor([19.8476, 19.0082, 20.2817, 18.2614])

In [37]:
# COS
a = torch.randn(4)
print(a)

torch.cos(a)

tensor([ 1.6060, -0.5652,  0.6357,  0.5081])


tensor([-0.0352,  0.8445,  0.8047,  0.8737])

In [38]:
# POW
a = torch.randn(4)
print(a)

torch.pow(a, 2)

tensor([-1.1973,  1.7811, -0.5124, -0.0199])


tensor([1.4334e+00, 3.1722e+00, 2.6253e-01, 3.9499e-04])

#### (3) Reduction Ops

In [39]:
# argmax
x = torch.tensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])

# It returns the indices of maxium value
torch.argmax(x)

tensor(8)

In [40]:
# argmin
print(torch.argmin(x))

x = torch.tensor([[1., 2., 3.], [4., 5., 0.], [7., 8., 9.]])
torch.argmin(x)

tensor(0)


tensor(5)

In [41]:
# sum
x = torch.tensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
torch.sum(x)

tensor(45.)

In [42]:
# unique
x = torch.tensor([[1., 1., 1.], [4., 5., 0.], [1., 1., 1.]])

torch.unique(x)

tensor([0., 1., 4., 5.])

#### (4) Comparison Ops

In [43]:
# eq 
torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True, False],
        [False,  True]])

In [44]:
# equal
torch.equal(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

False

In [45]:
torch.equal(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 2], [3, 4]]))

True

#### (5) Comparison Ops

In [46]:
# isinf
torch.isinf(torch.tensor([1, float('inf'), 2, float('-inf'), float('nan')]))

tensor([False,  True, False,  True, False])

In [47]:
# isnan
torch.isnan(torch.tensor([1, float('nan'), 2]))

tensor([False,  True, False])

### 4. Disabling gradient computation

In [48]:
x = torch.zeros(1, requires_grad=True)
with torch.no_grad():
    y = x * 2
print(y.requires_grad)

is_train = False
with torch.set_grad_enabled(is_train):
    y = x * 2
print(y.requires_grad)

torch.set_grad_enabled(True)  # this can also be used as a function
y = x * 2
print(y.requires_grad)

torch.set_grad_enabled(False)
y = x * 2
print(y.requires_grad)

False
False
True
False
