# Pytorch로 딥러닝 제대로 배우기-기초
## Part6: 모델(Model)
### 필수 라이브러리 Import

In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device


### 1. 모델 만들기

#### (1) 모델 구조 정의

In [2]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

#### (2) 모델 인스턴스화

In [3]:
model = NeuralNetwork().to(device)
print(model)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)


#### (3) 모델 살펴보기

In [4]:
# 1. parameters()
parms = model.parameters()

for parm in parms:
  print(parm.shape)

torch.Size([512, 784])
torch.Size([512])
torch.Size([512, 512])
torch.Size([512])
torch.Size([10, 512])
torch.Size([10])


In [5]:
# 2. named_parameters()
named_parms = model.named_parameters()

for name, param in named_parms:
  print("{}: {}".format(name, param.shape))

linear_relu_stack.0.weight: torch.Size([512, 784])
linear_relu_stack.0.bias: torch.Size([512])
linear_relu_stack.2.weight: torch.Size([512, 512])
linear_relu_stack.2.bias: torch.Size([512])
linear_relu_stack.4.weight: torch.Size([10, 512])
linear_relu_stack.4.bias: torch.Size([10])


In [6]:
# 3. state_dict
state_dict = model.state_dict()

for name, param in state_dict.items():
  print("{}: {}".format(name, param.shape))

linear_relu_stack.0.weight: torch.Size([512, 784])
linear_relu_stack.0.bias: torch.Size([512])
linear_relu_stack.2.weight: torch.Size([512, 512])
linear_relu_stack.2.bias: torch.Size([512])
linear_relu_stack.4.weight: torch.Size([10, 512])
linear_relu_stack.4.bias: torch.Size([10])


### 2. 다양한 모델 구성 방법

#### (1) 하나씩 선언하기

In [7]:
class OneByOneNetowrk(nn.Module):
    def __init__(self):
        super(OneByOneNetowrk, self).__init__()
        self.flatten = nn.Flatten()
        self.linear1 = nn.Linear(28*28, 512)
        self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(512, 512)
        self.relu2 = nn.ReLU()
        self.linear3 = nn.Linear(512, 10)

    def forward(self, x):
        x = self.flatten(x)
        x = self.linear1(x)
        x = self.relu(x)
        x = self.linear2(x)
        x = self.relu2(x)
        logits = self.linear3(x)
        return logits

In [8]:
one_by_one_model = OneByOneNetowrk().to(device)
print(one_by_one_model)

OneByOneNetowrk(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear1): Linear(in_features=784, out_features=512, bias=True)
  (relu1): ReLU()
  (linear2): Linear(in_features=512, out_features=512, bias=True)
  (relu2): ReLU()
  (linear3): Linear(in_features=512, out_features=10, bias=True)
)


In [9]:
import torch.nn.functional as F
class OneByOneNetowrk_v2(nn.Module):
    def __init__(self):
        super(OneByOneNetowrk_v2, self).__init__()
        self.flatten = nn.Flatten()
        self.linear1 = nn.Linear(28*28, 512)
        # self.relu1 = nn.ReLU()
        self.linear2 = nn.Linear(512, 512)
        # self.relu2 = nn.ReLU()
        self.linear3 = nn.Linear(512, 10)

    def forward(self, x):
        x = self.flatten(x)
        x = F.relu(self.linear1(x))
        x = F.relu(self.linear2(x))
        logits = self.linear3(x)
        return logits

In [10]:
one_by_one_model_v2 = OneByOneNetowrk_v2().to(device)
print(one_by_one_model_v2)

OneByOneNetowrk_v2(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear1): Linear(in_features=784, out_features=512, bias=True)
  (linear2): Linear(in_features=512, out_features=512, bias=True)
  (linear3): Linear(in_features=512, out_features=10, bias=True)
)


#### (2) Sequential() 활용하기

In [11]:
class SequentialNetwork(nn.Module):
    def __init__(self):
        super(SequentialNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.Dropout1d(),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [12]:
sequential_network = SequentialNetwork().to(device)
print(sequential_network)

SequentialNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): Dropout1d(p=0.5, inplace=False)
    (4): ReLU()
    (5): Linear(in_features=512, out_features=10, bias=True)
  )
)


In [13]:
class SequentialNetwork_v2(nn.Module):
    def __init__(self):
        super(SequentialNetwork_v2, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack1 = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU()
        )
        self.linear_relu_stack2 = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.Tanh(),
            nn.Linear(512, 512),
            nn.Tanh()
        )
        self.linear = nn.Linear(512*2, 10)

    def forward(self, x):
        x = self.flatten(x)
        out1 = self.linear_relu_stack1(x)
        out2 = self.linear_relu_stack2(x)
        out = torch.cat([out1, out2])
        logits = self.linear(out)
        return logits

In [14]:
sequential_network_v2 = SequentialNetwork_v2().to(device)
print(sequential_network_v2)

SequentialNetwork_v2(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack1): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
  )
  (linear_relu_stack2): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): Tanh()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): Tanh()
  )
  (linear): Linear(in_features=1024, out_features=10, bias=True)
)


#### (3) Model in Model

In [15]:
class SubNetwork(nn.Module):
    def __init__(self):
        super(SubNetwork, self).__init__()
        self.hidden = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU()
        )

    def forward(self, x):
        out = self.hidden(x)
        return out

In [16]:
class Model_in_Model(nn.Module):
    def __init__(self):
      super(Model_in_Model, self).__init__()
      self.flatten = nn.Flatten()
      self.hidden1 = SubNetwork()
      self.hidden2 = SubNetwork()
      self.fc = nn.Linear(512, 10)
    
    def forward(self, x):
      x = self.flatten(x)
      out1 = self.hidden1(x)
      out2 = self.hidden2(x)
      out = torch.cat([out1, out2])
      logit = self.fc(x)
      return logit

In [17]:
model_in_model = Model_in_Model().to(device)
print(model_in_model)

Model_in_Model(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (hidden1): SubNetwork(
    (hidden): Sequential(
      (0): Linear(in_features=784, out_features=512, bias=True)
      (1): ReLU()
      (2): Linear(in_features=512, out_features=256, bias=True)
      (3): ReLU()
    )
  )
  (hidden2): SubNetwork(
    (hidden): Sequential(
      (0): Linear(in_features=784, out_features=512, bias=True)
      (1): ReLU()
      (2): Linear(in_features=512, out_features=256, bias=True)
      (3): ReLU()
    )
  )
  (fc): Linear(in_features=512, out_features=10, bias=True)
)


### 3. Parameter 저장과 호출

#### (1) 모델 저장과 호출

In [18]:
# 1. 현재 모델의 parameter 저장 (추후 확인용)
old_model = model.state_dict()

# 2. 모델 저장
torch.save(model.state_dict(), 'model.pth')

In [19]:
# 3. 새로운 모델 생성
model = NeuralNetwork().to(device)
new_model = model.state_dict()

# 4. Check differences
for old, new in zip(old_model.items(), new_model.items()):
  print(old[1]-new[1])

tensor([[ 0.0034,  0.0474, -0.0263,  ..., -0.0007,  0.0305,  0.0143],
        [ 0.0138, -0.0339,  0.0045,  ...,  0.0046,  0.0068,  0.0020],
        [-0.0655, -0.0330,  0.0013,  ..., -0.0009,  0.0103, -0.0466],
        ...,
        [ 0.0157,  0.0160, -0.0008,  ..., -0.0164, -0.0141, -0.0123],
        [-0.0351, -0.0153,  0.0249,  ..., -0.0101, -0.0074,  0.0082],
        [-0.0458, -0.0136, -0.0265,  ..., -0.0026, -0.0127, -0.0166]],
       device='cuda:0')
tensor([ 3.7267e-02,  1.5558e-02,  1.6895e-02, -1.7661e-02, -2.9130e-02,
         3.1763e-02,  3.2874e-02, -9.4888e-03,  2.2784e-02,  1.1347e-02,
        -1.3426e-02,  4.9627e-02,  4.4657e-02, -3.1515e-02, -5.2496e-03,
        -5.8108e-02, -3.2248e-02,  1.9721e-02,  4.5053e-02, -3.2638e-02,
        -6.7972e-03, -4.3437e-02,  2.3158e-02, -1.4234e-02,  6.2362e-03,
         4.6974e-03,  5.5945e-02,  8.8029e-03, -2.5756e-02, -7.8262e-03,
        -2.3607e-02, -7.9952e-03, -1.7543e-02, -1.9945e-02,  3.3242e-03,
        -4.9663e-02,  2.6794e-0

In [20]:
# 5. Load the model
model.load_state_dict(torch.load('model.pth'))
new_model = model.state_dict()

# 6. Check differences
for old, new in zip(old_model.items(), new_model.items()):
  print(old[1]-new[1])

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0')
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 

#### (2) Optimizer 저장과 호출

In [21]:
from torch.optim import SGD

optimizer = SGD(model.parameters(), lr=0.01, momentum=0.9)
optim_state_dict = optimizer.state_dict()

for name, param in optim_state_dict.items():
  print("{}: {}".format(name, param)) 

state: {}
param_groups: [{'lr': 0.01, 'momentum': 0.9, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'params': [0, 1, 2, 3, 4, 5]}]


In [22]:
torch.save({
    'model': model.state_dict(),
    'optim': optimizer.state_dict()
}, 'model.pth')

In [23]:
load = torch.load('model.pth')
model.load_state_dict(load['model'])
optimizer.load_state_dict(load['optim'])

### 4. 학습 후 모델 저장과 호출

#### (1) 데이터 준비

In [24]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [25]:
# 공개된 데이터 셋으로부터 학습 데이터 다운로드 
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# 공개된 데이터 셋으로부터 테스트 데이터 다운로드
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)

  0%|          | 0/26421880 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/29515 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/4422102 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw



  0%|          | 0/5148 [00:00<?, ?it/s]

Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw



In [26]:
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

#### (2) 모델

In [27]:
class SequentialNetwork(nn.Module):
    def __init__(self):
        super(SequentialNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Dropout1d(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [28]:
model = SequentialNetwork().to(device)
model

SequentialNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Dropout1d(p=0.5, inplace=False)
    (5): Linear(in_features=512, out_features=10, bias=True)
  )
)

#### (3) Optimizer & Losses

In [29]:
# Optimizer
optimizer = SGD(model.parameters(), lr=0.01, momentum=0.9)

# losses
losses = nn.CrossEntropyLoss()

#### (4) 학습 & 테스트 wrapper

In [34]:
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train()
    print("Training mode: {}".format(model.training))
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss, current = loss.item(), batch * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

In [35]:
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval()
    print("Training mode: {}".format(model.training))
    test_loss, correct = 0, 0
    with torch.no_grad():
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")

#### (5) 학습

In [36]:
epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, losses, optimizer)
    test(test_dataloader, model, losses)
print("Done!")

Epoch 1
-------------------------------
mode: True
loss: 1.370905  [    0/60000]
loss: 1.570611  [ 6400/60000]
loss: 1.083844  [12800/60000]
loss: 1.376124  [19200/60000]
loss: 1.330090  [25600/60000]
loss: 1.256957  [32000/60000]
loss: 1.393317  [38400/60000]
loss: 1.434309  [44800/60000]
loss: 1.202441  [51200/60000]
loss: 1.399491  [57600/60000]
mode: False
Test Error: 
 Accuracy: 85.6%, Avg loss: 0.473472 

Epoch 2
-------------------------------
mode: True
loss: 1.108776  [    0/60000]
loss: 1.502575  [ 6400/60000]
loss: 1.065824  [12800/60000]
loss: 1.367121  [19200/60000]
loss: 1.422590  [25600/60000]
loss: 1.332101  [32000/60000]
loss: 1.203221  [38400/60000]
loss: 1.348959  [44800/60000]
loss: 1.279738  [51200/60000]
loss: 1.583028  [57600/60000]
mode: False
Test Error: 
 Accuracy: 86.0%, Avg loss: 0.473046 

Epoch 3
-------------------------------
mode: True
loss: 0.942005  [    0/60000]
loss: 1.111161  [ 6400/60000]
loss: 1.312426  [12800/60000]
loss: 1.433059  [19200/60000]

In [33]:
optim_state_dict = optimizer.state_dict()

for name, param in optim_state_dict.items():
  print("{}: {}".format(name, param)) 

state: {0: {'momentum_buffer': tensor([[-2.0692e-19, -1.2038e-11,  4.0997e-10,  ...,  2.5656e-05,
         -1.1377e-06, -1.1430e-07],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ..., -2.1108e-08,
         -1.6293e-08, -1.2865e-29],
        [-1.5414e-44,  3.4775e-15,  1.1116e-10,  ..., -4.6197e-04,
          1.1806e-06,  1.9202e-07],
        ...,
        [-4.4117e-31, -2.0536e-08, -6.7008e-11,  ...,  9.7344e-05,
         -2.3496e-06, -5.4882e-10],
        [-2.4059e-32, -3.3179e-09, -1.3639e-08,  ...,  1.2349e-07,
         -3.2031e-08,  3.4869e-22],
        [ 5.8292e-07, -1.3121e-07,  2.2037e-07,  ...,  2.0509e-04,
          1.9870e-05, -2.9363e-10]], device='cuda:0')}, 1: {'momentum_buffer': tensor([ 5.2154e-03, -1.0908e-04, -1.6070e-02,  1.3670e-03,  9.5878e-04,
        -4.9056e-04, -9.4697e-03, -1.4453e-02,  8.4895e-03,  1.0363e-02,
        -1.6422e-03,  6.9712e-03, -1.3125e-03, -1.1698e-03,  1.2543e-03,
        -9.1350e-03,  3.2455e-06, -5.2835e-03,  1.8007e-03, -5.6271e-03,
   